### ISSUE TITLE
Does 12labs SDK work in Vercel Edge Runtime?

### ISSUE THREAD

**Issue by louis030195** [twelvelabs-io/twelvelabs-js#33]
## Actual Behavior

```
Could not update database with video URL TypeError: Right-hand side of 'instanceof' is not an object
    at Index._request (webpack-internal:///(rsc)/./node_modules/.pnpm/twelvelabs-js@0.2.1/node_modules/twelvelabs-js/dist/core.js:81:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Index._get (webpack-internal:///(rsc)/./node_modules/.pnpm/twelvelabs-js@0.2.1/node_modules/twelvelabs-js/dist/core.js:98:17)
    at async Index.retrieve (webpack-internal:///(rsc)/./node_modules/.pnpm/twelvelabs-js@0.2.1/node_modules/twelvelabs-js/dist/resources/index/index.js:37:21)
    at async indexVideo (webpack-internal:///(rsc)/./lib/video/twelve-labs.ts:26:17)
    at async onUploadCompleted (webpack-internal:///(rsc)/./app/api/blob/route.ts:44:21)
    at async handleUpload (webpack-internal:///(rsc)/./node_modules/.pnpm/@vercel+blob@0.23.3/node_modules/@vercel/blob/dist/client.js:209:7)
    at async POST (webpack-internal:///(rsc)/./app/api/blob/route.ts:16:30)
    at async /Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53238
    at async e_.execute (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:44501)
    at async e_.handle (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:54492)
    at async doRender (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1372:42)
    at async cacheEntry.responseCache.get.routeKind (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1594:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1502:28)
    at async DevServer.renderPageComponent (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1919:24)
    at async DevServer.renderToResponseImpl (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1957:32)
    at async DevServer.pipeImpl (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:915:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:811:17)
    at async /Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/louisbeaumont/Documents/look-how-i-use-ai/node_modules/.pnpm/next@14.2.0_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/lib/start-server.js:141:13)
```

## Steps to Reproduce

1. use 12labs sdk in @vercel nextjs api route app router (retrieve index for example)

## Detailed Description

```ts
"use server";
import { TwelveLabs, Task } from "twelvelabs-js";

if (!process.env.TWELVE_LABS_API_KEY) {
  throw new Error("TWELVE_LABS_API_KEY is not set");
}

// Initialize the TwelveLabs client
const client = new TwelveLabs({
  apiKey: process.env.TWELVE_LABS_API_KEY!,
});

// Function to upload and index video
export async function indexVideo(fileUrl: string): Promise<string> {
  // create index if not existing
  console.log("indexing video", fileUrl);
  let index = await client.index.retrieve("default"); // <- CRASH HERE
  console.log("index", index);
  if (!index) {
    console.log("creating index");
    index = await client.index.create({
      name: "default",
      engines: [
        {
          name: "marengo2.6",
          options: ["visual", "conversation", "text_in_video"],
        },
        {
          name: "pegasus1",
          options: ["visual", "conversation"],
        },
      ],
    });
    console.log("index", index);
  }

  console.log(
    `Created index: id=${index.id} name=${index.name} engines=${JSON.stringify(
      index.engines
    )}`
  );
  let task: Task = await client.task.create({
    indexId: index.id,
    file: fileUrl,
  });

  console.log("task", task);
  task = await task.waitForDone();
  if (task.status !== "ready") {
    throw new Error(`Indexing failed with status ${task.status}`);
  }

  console.log("task", task);
  return task.videoId![0]; // Returns the unique video identifier
}

```
## Possible Solution

Make work in runtime people use (@vercel edge, deno, whaveter)

**Comment by louis030195** [comment]
how to fix: https://github.com/twelvelabs-io/twelvelabs-js/blob/38c6a6c9d686eb26f7f526cde6346b243e190818/src/core.ts#L1

use cross-fetch

https://www.npmjs.com/package/cross-fetch


https://vercel.com/docs/functions/runtimes/edge-runtime

**Comment by louis030195** [comment]
maybe u can check how openai did it too https://github.com/openai/openai-node
they used to be incompatible with edge but now it's compatible https://github.com/openai/openai-node?tab=readme-ov-file#requirements

**Comment by tl-genie** [comment]
Hey Louis, Thanks for your report. I'll be investigating this issue regarding to the node-fetch compatibility.

**Comment by tl-genie** [comment]
Your issue is addressed by [this change](https://github.com/twelvelabs-io/twelvelabs-js/pull/37). I'll let you know when we release new version including this change.
